### ISSUE TITLE
Login page for access authorization

### ISSUE THREAD

**Issue by PreetamSing** [okayshankha/tracetrail#13]
- I'm thinking about implementing this feature.  
And the best approach I can think of is user provides password to access [this page](https://camo.githubusercontent.com/babdab60dd137df80f9a8b53f2d54f1a5cc78a4ae5e4120e378df9e2bb64295c/68747470733a2f2f692e696d6775722e636f6d2f596c664e4d7a462e6a706567). That password (not password hash) is set in configuration while middleware initializaiton, picked up from environment variable desirably.  
@okayshankha  Do you have a better approach on your mind?

**Comment by okayshankha** [comment]
Yes, this is the plan I'm primarily having as well. We can do something like the following.

`const traceTrail = new TraceTrail('mongodb://localhost:27017/TraceTrail', {
   authorization: {
       username: String, // This value can be fetched from .env or some static value.
       password: String // This value can be fetched from .env or some static value.
   }
})`

**Comment by PreetamSing** [comment]
As we won't have multiple users or something like that, I think having `username` is just like making `password` lengthier for better security, for which we can just "make the `password` lengthier".

**Comment by okayshankha** [comment]
Yeah, this also works!

**Comment by PreetamSing** [comment]
#18
